In [4]:
mat = [[1,0,1],
      [1,1,0],
      [1,1,0]]

print(mat[:])


[[1, 0, 1], [1, 1, 0], [1, 1, 0]]


In [24]:
import numpy as np

mat = [[1,0,1],
      [1,1,0],
      [1,1,0]]

total = 0


arr = np.array(mat)

a,b = arr.shape
print(a)
print(b)

shapes = []
#getting all possible shaped of the matrix
for i in range(1, a + 1):
    for l in range(1, b + 1):
        shapes.append((i,l))

print(shapes)

for a,b in shapes:
    print(a,b)
    



print(arr[:,:1])

#Checking if all elements are 1s:

if np.all(arr[:,:1] == 1):
    print("all Ones")
else:
    print("Nope")


3
3
[(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3
[[1]
 [1]
 [1]]
all Ones


In [33]:
import numpy as np
mat = [[1,0,1],
      [1,1,0],
      [1,1,0]]

arr = np.array(mat)

#MATRIX LOOPING MODULE

#Test for 2x2 sub-matrix
n,p = arr.shape
print(n)
print(p)

a,b = 3,1


for rows in range( n-a  +1):
    for cols in range( p-b  +1):
        print(arr[rows:rows+a,cols:cols+b])

3
3
[[1]
 [1]
 [1]]
[[0]
 [1]
 [1]]
[[1]
 [0]
 [0]]


In [40]:
import numpy as np
mat = [[1,0,1],
      [1,1,0],
      [1,1,0]]

arr = np.array(mat)
n,p = arr.shape

shapes = []
total = 0


#getting all possible shaped of the matrix
for i in range(1, n + 1):
    for l in range(1, p + 1):
        shapes.append((i,l))

print(shapes)

print("-----------------------------------")

for a,b in shapes:
    print("+++++++++")
    print(a,b)
    for rows in range( n-a  +1):
        for cols in range( p-b  +1):
            print(arr[rows:rows+a,cols:cols+b])
            if np.all(arr[rows:rows+a,cols:cols+b] == 1):
                total += 1
            
print("Final answer:", end = " ")
print(total)
#MATRIX LOOPING MODULE
a,b = 3,1
print("-----------------------------------")

for rows in range( n-a  +1):
    for cols in range( p-b  +1):
        print(arr[rows:rows+a,cols:cols+b])

[(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
-----------------------------------
+++++++++
1 1
[[1]]
[[0]]
[[1]]
[[1]]
[[1]]
[[0]]
[[1]]
[[1]]
[[0]]
+++++++++
1 2
[[1 0]]
[[0 1]]
[[1 1]]
[[1 0]]
[[1 1]]
[[1 0]]
+++++++++
1 3
[[1 0 1]]
[[1 1 0]]
[[1 1 0]]
+++++++++
2 1
[[1]
 [1]]
[[0]
 [1]]
[[1]
 [0]]
[[1]
 [1]]
[[1]
 [1]]
[[0]
 [0]]
+++++++++
2 2
[[1 0]
 [1 1]]
[[0 1]
 [1 0]]
[[1 1]
 [1 1]]
[[1 0]
 [1 0]]
+++++++++
2 3
[[1 0 1]
 [1 1 0]]
[[1 1 0]
 [1 1 0]]
+++++++++
3 1
[[1]
 [1]
 [1]]
[[0]
 [1]
 [1]]
[[1]
 [0]
 [0]]
+++++++++
3 2
[[1 0]
 [1 1]
 [1 1]]
[[0 1]
 [1 0]
 [1 0]]
+++++++++
3 3
[[1 0 1]
 [1 1 0]
 [1 1 0]]
Final answer: 13
-----------------------------------
[[1]
 [1]
 [1]]
[[0]
 [1]
 [1]]
[[1]
 [0]
 [0]]


In [41]:
import numpy as np
mat = [[1,0,1],
      [1,1,0],
      [1,1,0]]

arr = np.array(mat)
n,p = arr.shape

shapes = []
total = 0


#getting all possible shaped of the matrix
for i in range(1, n + 1):
    for l in range(1, p + 1):
        shapes.append((i,l))

print(shapes)

print("-----------------------------------")

for a,b in shapes:
    print("+++++++++")
    print(a,b)
    for rows in range( n-a  +1):
        for cols in range( p-b  +1):
            print(arr[rows:rows+a,cols:cols+b])
            if np.all(arr[rows:rows+a,cols:cols+b] == 1):
                total += 1
            
print("Final answer:", end = " ")
print(total)


[(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
-----------------------------------
+++++++++
1 1
[[1]]
[[0]]
[[1]]
[[1]]
[[1]]
[[0]]
[[1]]
[[1]]
[[0]]
+++++++++
1 2
[[1 0]]
[[0 1]]
[[1 1]]
[[1 0]]
[[1 1]]
[[1 0]]
+++++++++
1 3
[[1 0 1]]
[[1 1 0]]
[[1 1 0]]
+++++++++
2 1
[[1]
 [1]]
[[0]
 [1]]
[[1]
 [0]]
[[1]
 [1]]
[[1]
 [1]]
[[0]
 [0]]
+++++++++
2 2
[[1 0]
 [1 1]]
[[0 1]
 [1 0]]
[[1 1]
 [1 1]]
[[1 0]
 [1 0]]
+++++++++
2 3
[[1 0 1]
 [1 1 0]]
[[1 1 0]
 [1 1 0]]
+++++++++
3 1
[[1]
 [1]
 [1]]
[[0]
 [1]
 [1]]
[[1]
 [0]
 [0]]
+++++++++
3 2
[[1 0]
 [1 1]
 [1 1]]
[[0 1]
 [1 0]
 [1 0]]
+++++++++
3 3
[[1 0 1]
 [1 1 0]
 [1 1 0]]
Final answer: 13


In [57]:
import numpy as np
mat = [[1,0,1],
      [1,1,0],
      [1,1,0]]

arr = np.array(mat)
print(arr.size)

print(arr[1:3,0:2])

for elem in arr[1:3,0:2]:
    if elem.any():
        print( False)
    else:
        print( True)

9
[[1 1]
 [1 1]]
False
False
