In [ ]:
import numpy as np

In [10]:
a  = np.array([[ 0.,  0.,  0.],
               [ 0.,  0.,  0.],
               [ 0.,  0.,  0.]])
x = np.ones(3)

a[:,1] = x

print(a)


[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [31]:
arr = [[0,1,1],
      [1,1,1],
      [1,0,1]]
arr = np.array(arr)
print(arr)



[[0 1 1]
 [1 1 1]
 [1 0 1]]


In [32]:
result = np.where(arr == 0)
result_row = result[0]
result_column = result[1] 
print(result_row)
print(result_column)

[0 2]
[0 1]


In [27]:
arr[1,:] = 0
print(arr)


[[0 1 1]
 [0 0 0]
 [1 0 1]]


In [33]:
for i in result_row:
    arr[i,:] = 0
for i in result_column:
    arr[:,i] = 0
    

In [34]:
print(arr)

[[0 0 0]
 [0 0 1]
 [0 0 0]]


In [38]:
arr = [[0,1,1],
      [1,1,1],
      [1,0,1]]

for i in arr[0]:
    i = 0
print(arr)

[[0, 1, 1], [1, 1, 1], [1, 0, 1]]
